In [1]:
import tensorflow as tf
import numpy as np

In [2]:
data = np.loadtxt('./data.csv', delimiter=',',
                  unpack=True, dtype='float32')

In [4]:
data

array([[ 0.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.]], dtype=float32)

In [3]:
print(data[0:2])
print(data[2:])

[[ 0.  1.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  1.]]
[[ 1.  0.  0.  1.  1.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  1.]]


In [5]:
x_data = np.transpose(data[0:2])
y_data = np.transpose(data[2:])

In [6]:
print(x_data)
print(y_data)

[[ 0.  0.]
 [ 1.  0.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
